walter-modem/CMakeLists.txt
partially fixes the problem described in #2
=> fix esp_vfs_fat.h not found / suppress compiler errors

examples/socket_test/main/socket_test.cpp, src/WalterModem.cpp, src/WalterModem.h
this PR aims to add the ability to registers handlers for certain types of events,
such as connection events etc.
closes #15
=> Callback support

examples/socket_test/main/socket_test.cpp, src/WalterModem.cpp, src/WalterModem.h
This pull request contains the following changes:
- Updated the code to be 100 columns wide instead of 80
- Integrated the GNSS events into the new eventing system
- Updated the internal eventing system to be type safe
- Renamed some buffer size defines for consistency
=> Update eventing system and changed to 100 columns code width.

CHANGELOG.md, examples/bluecherry/main/idf_component.yml, examples/coap/main/idf_component.yml, examples/http/main/idf_component.yml, examples/mqtt/main/idf_component.yml, examples/positioning/main/idf_component.yml, examples/udp_socket/main/idf_component.yml
=> reverted version number

src/WalterModem.h, src/proto/WalterMQTT.cpp
=> fixed mqttConfig wrong default params

CHANGELOG.md, src/WalterModem.cpp
=> fixed out of bounds compiler error in release mode

src/proto/WalterSocket.cpp
=> removed redundant PDP getter

src/WalterModem.h, src/proto/WalterSocket.cpp
=> added protocol option to socketListen command

src/WalterModem.cpp
=> fixed wrong dataStart for SQNSRING

src/WalterModem.h, src/proto/WalterSocket.cpp
=> fixed _atNum bug in socketReceive

src/WalterModem.h
=> updated definePDPContext documentation

src/WalterModem.h
=> made tlsWriteCredential public

CHANGELOG.md, README.md, examples/bluecherry/main/idf_component.yml, examples/coap/main/idf_component.yml, examples/http/main/idf_component.yml, examples/mqtt/main/idf_component.yml, examples/positioning/main/idf_component.yml, examples/udp_socket/main/idf_component.yml, idf_component.yml
This pull request contains all the neccesary changes for the 1.2.1 maintenance release on ESP-IDF
=> release 1.2.1

examples/bluecherry/main/bluecherry_example.cpp
=> fix: added delay to blucherry sync loop

src/WalterModem.h, src/proto/WalterHTTP.cpp
closes quickspot/walter-arduino#20
=> Fix quickspot/walter-arduino#20

src/WalterModem.h, src/proto/WalterSocket.cpp
=> feat(socket): add datareceived param to socketReceive.

src/WalterModem.cpp
=> fix(socket): bug where didRIng flag was not reset

src/proto/WalterSocket.cpp
the ring flag was not reset when using didRing method in dataview mode
=> fix(socket): didRing flag not reset when reading using dataview mode

src/WalterModem.h, src/proto/WalterHTTP.cpp
=> feat(http): add support for extra header line

examples/udp_socket/main/socket_example.cpp, src/WalterModem.cpp, src/WalterModem.h, src/proto/WalterSocket.cpp
added suuport for socketGetStates
=> feat(socket): socketGetState,  _socketUpdateStates

src/WalterModem.h, src/proto/WalterSocket.cpp
this PR adds support for the SQNSO at command.
=> feat(socket): add socket resume

src/WalterModem.cpp
Upped the UART treshold from 128 * 0.8 (~102) to 122
=> fix(uart): hardware flow control threshold

src/proto/WalterMQTT.cpp
https://github.com/QuickSpot/walter-arduino/pull/87
=> update src from arduino
